// Price alarms placed on charts. Each alarm has its own id, a price set by the
// user, the associated ticker, and the strategy of the zone/chart it was drawn
// from. Triggering is intentionally NOT implemented yet — this just stores the
// level cleanly so it can be armed in a later iteration.

use rusqlite::{params, Connection, Result};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PriceAlarm {
    pub id: String,
    pub symbol: String,
    pub strategy_id: Option<String>,
    pub price: f64,
    pub created_at: String,
    /// Set the moment the price crosses the level. None = still armed.
    pub triggered_at: Option<String>,
}

/// Insert a new alarm. The id is generated by the caller (frontend UUID).
pub fn insert(
    conn: &Connection,
    id: &str,
    symbol: &str,
    strategy_id: Option<&str>,
    price: f64,
) -> Result<PriceAlarm> {
    conn.execute(
        "INSERT INTO price_alarms (id, symbol, strategy_id, price) VALUES (?1, ?2, ?3, ?4)",
        params![id, symbol, strategy_id, price],
    )?;
    get(conn, id).map(|o| {
        o.unwrap_or(PriceAlarm {
            id: id.to_string(),
            symbol: symbol.to_string(),
            strategy_id: strategy_id.map(String::from),
            price,
            created_at: String::new(),
            triggered_at: None,
        })
    })
}

const COLS: &str = "id, symbol, strategy_id, price, created_at, triggered_at";

pub fn get(conn: &Connection, id: &str) -> Result<Option<PriceAlarm>> {
    let sql = format!("SELECT {COLS} FROM price_alarms WHERE id=?1");
    let mut stmt = conn.prepare(&sql)?;
    let mut rows = stmt.query_map(params![id], row_to_alarm)?;
    rows.next().transpose()
}

/// All alarms for a ticker (most recent first).
pub fn get_for_symbol(conn: &Connection, symbol: &str) -> Result<Vec<PriceAlarm>> {
    let sql = format!("SELECT {COLS} FROM price_alarms WHERE symbol=?1 ORDER BY created_at DESC");
    let mut stmt = conn.prepare(&sql)?;
    let rows = stmt.query_map(params![symbol], row_to_alarm)?;
    rows.collect()
}

/// Every alarm across all tickers (most recent first).
pub fn get_all(conn: &Connection) -> Result<Vec<PriceAlarm>> {
    let sql = format!("SELECT {COLS} FROM price_alarms ORDER BY created_at DESC");
    let mut stmt = conn.prepare(&sql)?;
    let rows = stmt.query_map([], row_to_alarm)?;
    rows.collect()
}

/// Armed alarms only (not yet triggered) — what the scanner watches.
pub fn get_untriggered(conn: &Connection) -> Result<Vec<PriceAlarm>> {
    let sql = format!("SELECT {COLS} FROM price_alarms WHERE triggered_at IS NULL");
    let mut stmt = conn.prepare(&sql)?;
    let rows = stmt.query_map([], row_to_alarm)?;
    rows.collect()
}

/// Stamp an alarm as triggered so it won't fire again.
pub fn mark_triggered(conn: &Connection, id: &str) -> Result<()> {
    conn.execute(
        "UPDATE price_alarms SET triggered_at=datetime('now') WHERE id=?1",
        params![id],
    )?;
    Ok(())
}

pub fn delete(conn: &Connection, id: &str) -> Result<()> {
    conn.execute("DELETE FROM price_alarms WHERE id=?1", params![id])?;
    Ok(())
}

fn row_to_alarm(r: &rusqlite::Row) -> Result<PriceAlarm> {
    Ok(PriceAlarm {
        id: r.get(0)?,
        symbol: r.get(1)?,
        strategy_id: r.get(2)?,
        price: r.get(3)?,
        created_at: r.get(4)?,
        triggered_at: r.get(5)?,
    })
}
