// Persisted bug reports. Survive across launches (replaces the old in-RAM list).
// priority: 1 = low, 2 = medium, 3 = high. Listed high → low, then newest first.

use rusqlite::{params, Connection, Result};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BugReport {
    pub id: String,
    pub text: String,
    pub priority: i64,
    pub created_at: String,
}

/// Insert a new bug report. The id is generated by the caller (frontend UUID).
pub fn insert(conn: &Connection, id: &str, text: &str, priority: i64) -> Result<()> {
    conn.execute(
        "INSERT INTO bug_reports (id, text, priority) VALUES (?1, ?2, ?3)",
        params![id, text, priority],
    )?;
    Ok(())
}

/// All bug reports sorted by priority (high first) then most recent.
pub fn get_all(conn: &Connection) -> Result<Vec<BugReport>> {
    let mut stmt = conn.prepare(
        "SELECT id, text, priority, created_at FROM bug_reports
         ORDER BY priority DESC, created_at DESC",
    )?;
    let rows = stmt.query_map([], |r| {
        Ok(BugReport {
            id: r.get(0)?,
            text: r.get(1)?,
            priority: r.get(2)?,
            created_at: r.get(3)?,
        })
    })?;
    rows.collect()
}

pub fn delete(conn: &Connection, id: &str) -> Result<()> {
    conn.execute("DELETE FROM bug_reports WHERE id=?1", params![id])?;
    Ok(())
}

pub fn clear_all(conn: &Connection) -> Result<()> {
    conn.execute("DELETE FROM bug_reports", [])?;
    Ok(())
}
